### Login
POST /api/login HTTP/1.1
Host: localhost:3001
Content-Type: application/json

{
	"email": "test@test.com",
	"password": "test"
}

###
POST /api/login HTTP/1.1
Host: localhost:3001
Content-Type: application/json

{
	"email": "admin@admin.com",
	"password": "admin"
}

### Register
POST /api/register HTTP/1.1
Host: localhost:3001
Content-Type: application/json

{
	"name": "admin",
	"email": "admin@admin.com",
	"password": "admin"
}