###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpZCI6IjY1NjQ4NzY5MmE3OGExNGZiMGRkNzYxZCIsImlhdCI6MTcwMTA4NzI1NiwiZXhwIjoxNzAxNjkyMDU2fQ.035qG3Er1FviVx8_r7MP-emKYk4IsB9sfIgIgTJW5f0

@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlkIjoiNjU2NDg4ODhiNmVhZTYzNjBhYTQ2NTc5IiwiaWF0IjoxNzAxMDg3NDEwLCJleHAiOjE3MDE2OTIyMTB9.Z1Y_Dtvfv80Tpd5chR0KJyIxncPSgNvm0egJP9mF7zw

@postId = 65648832b6eae6360aa46571
###

### Add comment
POST /api/comments/{{postId}} HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
	"content": "Comentario del admin"
}