###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpZCI6IjY1NjBhNzk5YjVlOWUxNzFiMTcyYjhlMiIsImlhdCI6MTcwMDk0NDM3M30.9Yp4nyxGWGSqDyXGXT9sebWDIDJhV9SLL-XC2D9Oqf
###

### Add comment
POST /api/comments/6561f89360772d277d390082 HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Authorization: Bearer {{token}}

{
	"content": "segundo comentarioo"
}