###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpZCI6IjY1NjQ4NzY5MmE3OGExNGZiMGRkNzYxZCIsImlhdCI6MTcwMTA4NzI1NiwiZXhwIjoxNzAxNjkyMDU2fQ.035qG3Er1FviVx8_r7MP-emKYk4IsB9sfIgIgTJW5f0

### Get all posts
GET /api/posts HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Authorization: Bearer {{token}}

### Get a post with ID
GET /api/posts/65648832b6eae6360aa46571 HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Authorization: Bearer {{token}}

### Create a post
POST /api/posts HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Authorization: Bearer {{token}}

{
	"title": "Post 1",
	"description": "Description 1",
	"imageUrl": "https://picsum.photos/200/300",
	"location": "Location 1"
}

### Update a post
PUT /api/posts/6561f89360772d277d390082 HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Authorization: Bearer {{token}}

{
	"title": "Post 1",
	"description": "Post actualizado 18:08",
	"imageUrl": "https://picsum.photos/200/300",
	"location": "Location 1"
}

### Delete a post
DELETE /api/posts/6562603432c8aaa0ccf1a3a9 HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Authorization: Bearer {{token}}
