###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5pY29sYXNAcm9kcmlndWV6LmNvbSIsImlkIjoiNjU1ZmM1MmNiNmUwOTc2OTBhYjhkZjRhIiwiaWF0IjoxNzAwNzc3NzY0fQ.0PxZAN1LCvvDdeyax_MPp430WHtlL2vQp0Z7dv_VJik
###

### Get all posts
GET /api/posts HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Authorization: Bearer {{token}}

### Get a post with ID
GET /api/posts/6561f89360772d277d390082 HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Authorization: Bearer {{token}}

### Create a post
POST /api/posts HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Authorization: Bearer {{token}}

{
	"title": "Post 1",
	"description": "Post 1 description",
	"imageUrl": "https://picsum.photos/200/300",
	"location": "Location 1"
}